export const environment = {
  production: true,
  api: '/api',
  geoserverApi: 'https://indices.jalisco.gob.mx/geoserver',
  workspaceIieg: 'iieg',
  workspaceCovid: 'covid19',
  workspaceSej: 'sej',
  warehouse: 'iieg',
  outputJson: 'outputFormat=application/json',
  requestFeature: 'request=GetFeature',
  wfsService: 'service=WFS',
  version: 'version=1.0.0',
  activosxmpiograf: 'activosxmpiograf',
  activosxmpiograf_7_14: 'activosxmpiograf_7_14',
  activosacumedades: 'activosacumedades',
  defacumedades: 'defacumedades',
  typeNameFechas: 'typeName=activosxmpiograf',
  maxFeatures: 'maxFeatures=1',
  baseUrl: 'https://swapi.dev/api/people/'
};
